In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/cardio-vascular-disease-detection/CardiovascularDiseaseDetection.docx
/kaggle/input/cardio-vascular-disease-detection/cardio_train.csv
/kaggle/input/cardiotrain/cardio_train.xlsx
/kaggle/input/my-data-train/cardio_train.csv


In [6]:
train_data=pd.read_csv('/kaggle/input/my-data-train/cardio_train.csv')
train_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  988  22469       1     155    69.0    130     80            2     2      0   
1  989  14648       1     163    71.0    110     70            1     1      0   
2  990  21901       1     165    70.0    120     80            1     1      0   
3  991  14549       2     165    85.0    120     80            1     1      1   
4  992  23393       1     155    62.0    120     80            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       1       0  
3     1       1       0  
4     0       1       0

In [7]:
train_data.dtypes

id               int64
age              int64
gender           int64
height           int64
weight         float64
ap_hi            int64
ap_lo            int64
cholesterol      int64
gluc             int64
smoke            int64
alco             int64
active           int64
cardio           int64
dtype: object

In [8]:
train_data.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='object')

In [9]:
count = train_data[['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio']].isna().sum()
count

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [14]:
x_train=np.asarray(train_data[['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active']]).astype('int64')
x_train[0:5]

array([[22469,     1,   155,    69,   130,    80,     2,     2,     0,
            0,     1],
       [14648,     1,   163,    71,   110,    70,     1,     1,     0,
            0,     1],
       [21901,     1,   165,    70,   120,    80,     1,     1,     0,
            0,     1],
       [14549,     2,   165,    85,   120,    80,     1,     1,     1,
            1,     1],
       [23393,     1,   155,    62,   120,    80,     1,     1,     0,
            0,     1]])

In [15]:
y_train=np.asarray(train_data['cardio'])
y_train[0:5]

array([0, 1, 0, 0, 0])

In [20]:
test_id=int(input('enter the id of the patient: '))
f=int(input('enter the age of the patient: '))
test_age=f*365
test_gender=int(input('enter the gender of the patient- 0:male, 1:female: '))
test_height=int(input('enter the height of the patient: '))
test_weight=int(input('enter the weight of the patient: '))
test_ap_hi=int(input('enter the systolic blood pressure of the patient: '))
test_ap_lo=int(input('enter the diastolic blood pressure of the patient: '))
test_cholesterol=int(input('enter the cholesterol level of the patient- 1: normal, 2: above normal, 3: well above normal: '))
test_gluc=int(input('enter the glucose level of the patient- 1: normal, 2: above normal, 3: well above normal: '))
test_smoke=int(input('enter 0: if patient does not smoke, 1: if patient smokes: '))
test_alco=int(input('enter 0: if patient does not take alcohol, 1: if patient takes alcohol: '))
test_active=int(input('enter 0: if patient does not indulge in physical activities, 1: if patient indulges in physical activities: '))

enter the id of the patient860
enter the age of the patient18
enter the gender of the patient- 0:male, 1:female1
enter the height of the patient167
enter the weight of the patient54
enter the systolic blood pressure of the patient110
enter the diastolic blood pressure of the patient90
enter the cholestrol leve of the patient- 1: normal, 2: above normal, 3: well above normal1
enter the glucose level of the patient- 1: normal, 2: above normal, 3: well above normal2
enter 0: if patient does not smoke, 1: if patient smokes0
enter 0: if patient does not take alcohol, 1: if patient takes alcohol1
enter 0: if patient does not indulge in physical activities, 1: if patient indulges in physical activities1


In [26]:
x_test=np.array([[test_age, test_gender, test_height, test_weight, test_ap_hi, test_ap_lo,test_cholestrol, test_gluc, test_smoke, test_alco, test_active]])
x_test

array([[6570,    1,  167,   54,  110,   90,    1,    2,    0,    1,    1]])

In [29]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(x_train, y_train)
predictions = model.predict(x_test)
print("Patient id:",test_id)
print('Report: ',end='')
if predictions==0:
    print('Patient does not have cardio vascular disease')
else:
    print("Patient has cardio vascular disease")

id= 860
Patient does not have cardio vascular disease
